my:
  app:
    appVersion: v1.0.0
    app_test: Test
    default-language: tr
    default-names:
      - osman
      - ali
      - veli
      - mehmet
      - mahmut
    department:
      distance: 30
      location: istanbul
      name: IT
    departments:
      - distance: 20
        location: istanbul
        name: Sale
      - distance: 300
        location: ankara
        name: HR
    response-timeout: 1000
    department-map:
      hr:
        name: hr
        location: izmir
        distance: 400
      tck:
        name: tck
        location: adana
        distance: 1000
server:
  port: 8899
  shutdown: graceful
spring:
  profiles:
    active: tr
    default: tr
  lifecycle:
    timeout-per-shutdown-phase: 5m
management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
      show-components: always
    env:
      show-values: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
info:
  test:
    mest:
      value: 1
      another-value: 2
    app:
      version: 1
      text: denem
      pom-version: '@project.version@'
